name: joblyx_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  go_router: ^17.0.1
  google_fonts: ^7.0.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.26.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/rocket.png
    - assets/images/discuss.png
    - assets/images/document.png
    - assets/images/location.png
    - assets/images/logo.png
    - assets/images/logo_1.png
    - assets/images/logo_j.png
    - assets/images/linkedin_logo.svg
    - assets/images/profile.png
    - assets/i18n/en.json
    - assets/i18n/fr.json
    - .env
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
